### ISSUE TITLE
'undefined reference to symbol' error during linking RSMI on linux

### ISSUE THREAD

**Issue by TerkaSlaninakova** [Liuguanli/RSMI#2]
Hi! I'm having trouble linking the repo on my linux environment. I'm getting the following error:
```
/usr/bin/ld: Exp.o: undefined reference to symbol '_ZTTN5torch2nn10LinearImplE'
/usr/bin/ld: //storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/lib/libtorch_cpu.so: error adding symbols: DSO missing from command line
```

I am working on Debian 4.19.194 with the most recent LibTorch (CPU) ver. 1.10.0 - I tried both Pre-cxx11 ABI and cxx11 ABI variants (both producing the same error), gcc version 8.3.0 and boost version 1.60.

I followed the instructions in README, replacing the libtoch path with my own, without changing anything else.
I also tried older libtorch versions, the linking error can be traced back to 1.5.0, in which case the missing reference symbol is '_ZTVN5torch5optim11AdamOptionsE'. Versions <1.5.0 fail even earlier in the compilation.

The entire compilation output:
```
(BUSTER)tslaninakova@skirit:/storage/brno6/home/tslaninakova/playground/RSMI$ make -f Makefile
g++ -O3 -std=c++14 -o Exp.o -c Exp.cpp -g -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include/torch/csrc/api/include
g++ -O3 -std=c++14 -o utils/FileReader.o -c utils/FileReader.cpp -g -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include/torch/csrc/api/include
g++ -O3 -std=c++14 -o utils/ExpRecorder.o -c utils/ExpRecorder.cpp -g -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include/torch/csrc/api/include
g++ -O3 -std=c++14 -o utils/Constants.o -c utils/Constants.cpp -g -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include/torch/csrc/api/include
g++ -O3 -std=c++14 -o utils/FileWriter.o -c utils/FileWriter.cpp -g -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include/torch/csrc/api/include
g++ -O3 -std=c++14 -o entities/Mbr.o -c entities/Mbr.cpp -g -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include/torch/csrc/api/include
g++ -O3 -std=c++14 -o entities/NonLeafNode.o -c entities/NonLeafNode.cpp -g -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include/torch/csrc/api/include
g++ -O3 -std=c++14 -o entities/LeafNode.o -c entities/LeafNode.cpp -g -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include/torch/csrc/api/include
g++ -O3 -std=c++14 -o entities/NodeExtend.o -c entities/NodeExtend.cpp -g -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include/torch/csrc/api/include
g++ -O3 -std=c++14 -o entities/Point.o -c entities/Point.cpp -g -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include/torch/csrc/api/include
g++ -O3 -std=c++14 -o entities/Node.o -c entities/Node.cpp -g -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include/torch/csrc/api/include
g++ -O3 -std=c++14 -o curves/hilbert.o -c curves/hilbert.cpp -g -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include/torch/csrc/api/include
g++ -O3 -std=c++14 -o curves/z.o -c curves/z.cpp -g -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include/torch/csrc/api/include
g++ -O3 -std=c++14 -o curves/hilbert4.o -c curves/hilbert4.cpp -g -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include/torch/csrc/api/include
g++ -O3 -std=c++14 -o Exp Exp.o utils/FileReader.o utils/ExpRecorder.o utils/Constants.o utils/FileWriter.o entities/Mbr.o entities/NonLeafNode.o entities/LeafNode.o entities/NodeExtend.o entities/Point.o entities/Node.o curves/hilbert.o curves/z.o curves/hilbert4.o -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include -I/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/include/torch/csrc/api/include -L/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/lib -ltorch -lc10 -lpthread -Wl,-rpath=/storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/lib
/usr/bin/ld: Exp.o: undefined reference to symbol '_ZTTN5torch2nn10LinearImplE'
/usr/bin/ld: //storage/brno6/home/tslaninakova/playground/RSMI/libtorch-abi/lib/libtorch_cpu.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:35: Exp] Error 1
```

Any suggestions are greatly appreciated.

**Comment by TerkaSlaninakova** [comment]
The problem disappeared once I put the `ltorch_cpu` flag in the Makefile, so:
```
#for linux
...
LIB +=-L/opt/libtorch/lib -ltorch -ltorch_cpu -lc10 -lpthread
```

**Comment by lamianshifu** [comment]
> 

similar problem and also fixed by the same way
